Progress:   0%|                                                                                              | 0/90 [00:00<?, ?it/s]

















































































































































































































































Traceback (most recent call last):
  File "main.py", line 146, in <module>
    init_and_train_model(args.verbose)
  File "main.py", line 106, in init_and_train_model
    DeepSeg.train_model()
  File "/root/research/deep-segmentation/segmentation/segmentation.py", line 253, in train_model
    training_losses, validation_losses, lr_rates = trainer.run_trainer()
  File "/root/research/deep-segmentation/segmentation/trainer.py", line 67, in run_trainer
    wandb.save(os.path.join(pathlib.Path.cwd(), model_name), base_path="/mnt")
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_run.py", line 1403, in save
    raise ValueError("globs can't walk above base_path")
ValueError: globs can't walk above base_path